### ISSUE TITLE
Testing Feedback from Bethany

### ISSUE THREAD

**Issue by wguldin** [IntuitiveWebSolutions/BriteApps-Admin-Element#13]
**Some actions items out of our meeting:** 
- [x] Hide sections that have no search results while search string is active
- [x] `Position: Fixed` search bar as you scroll, so it's easy to see if you have an active search. 
- [x] Index more information in search tool. 
    - Should be possible to include module name in the search, so a search for 'dashboard' should show all pieces in the dashboard section, even if they don't mention the word dashboard directly.
- [x] Alphabetize sidebar listings
- [x] Button to easily 'clear' a search
- [x] Allow panels to be collapsed.
- [x] Add filter that only shows your 'overrides', i.e. values that don't match the default text.

Also, not really an action item, but the build section seemed to log us out immediately once clicking on it, maybe it's just not quite ready yet. 

Thanks Gleb!

**Comment by gleb-britecore** [comment]
This should all be fixed
